version: '3.2'

services:
  app:
    build: .
    volumes:
      - ./app:/app/app
      - ./babel.config.js:/app/babel.config.js
      - ./nodemon.json:/app/nodemon.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/dist
      - /app/node_modules
    ports:
      - '8080:8080'
      - '35729:35729'
