version: '3.2'

services:
  app:
    build: .
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./babel.config.json:/app/babel.config.json
      - ./index.js:/app/index.js
      - ./nodemon.json:/app/nodemon.json
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - /app/dist
      - /app/node_modules
    ports:
      - '8080:8080'
      - '35729:35729'
